### ISSUE TITLE
Automator says USB is patched despite errors (install-setvars failed, SOLVED)

### ISSUE THREAD

**Issue by Mennaruuk** [moosethegoose2213/automator-for-barrykn-micropatcher#1]
I've been having issues manually patching my USB drive, [mainly with install-setvars](https://github.com/barrykn/big-sur-micropatcher/issues/142), so I resorted to using the Automator. (By the way, it's awesome, and I hope one day it is actually implemented in barrykn's.) I was pleasantly surprised when it informed me that the USB flash drive was successfully patched. However, when I restarted and held the Option button, I couldn't find EFI Boot, meaning there was an error setting up `setvars`. But Automator didn't mention this error.

Is there a way to have Automator spit out some kind of log or notify the user that an error has occurred? For example, it can detect if the log says "`install-setvars` cannot continue" so it spits out that error, or something like that.

One other feature suggestion is having a progress bar for createinstallmedia. I did see it working behind the scenes in Activity Monitor, but having some kind of indicator that it's ongoing would be a nice GUI touch.

**Comment by moosethegoose2213** [comment]
Downloading and running the micropatcherautomator.sh file will do the "verbose" version of the automation process. Another thing to try is redonwnloading the micropatcher, then rerunning the Automator.

**Comment by moosethegoose2213** [comment]
> One other feature suggestion is having a progress bar for createinstallmedia. I did see it working behind the scenes in Activity Monitor, but having some kind of indicator that it's ongoing would be a nice GUI touch.

I also just noticed the suggestion for a progress bar for createinstallmedia. I would really like to have one, but I haven't managed to get one to work. If you have any suggestions on how to do it, please let me know. And has your issue with install-setvars been resolved?

**Comment by ghost** [comment]
I wish I knew some coding, but I know absolutely nothing, I probably shouldn’t even be on GitHub 😅 Even TINU, which is essentially a GUI to create bootable disks, doesn’t have a progress bar.
![2EB87B4D-485F-4BDB-99CB-DE52F9FB4C1B](https://user-images.githubusercontent.com/52135169/101819080-c49c3400-3af2-11eb-9b48-0c6934266b6e.jpeg)

And yes, I got the issue resolved!!!

**Comment by moosethegoose2213** [comment]
> I wish I knew some coding, but I know absolutely nothing, I probably shouldn’t even be on GitHub 😅 Even TINU, which is essentially a GUI to create bootable disks, doesn’t have a progress bar.
> ![2EB87B4D-485F-4BDB-99CB-DE52F9FB4C1B](https://user-images.githubusercontent.com/52135169/101819080-c49c3400-3af2-11eb-9b48-0c6934266b6e.jpeg)
> 
> And yes, I got the issue resolved!!!

Nice! I plan on closing this issue soon, but I'd like to know what you did to solve it if you have time. That way if someone has a similar issue I can assist them in the future

**Comment by ghost** [comment]
> > I wish I knew some coding, but I know absolutely nothing, I probably shouldn’t even be on GitHub 😅 Even TINU, which is essentially a GUI to create bootable disks, doesn’t have a progress bar.
> > ![2EB87B4D-485F-4BDB-99CB-DE52F9FB4C1B](https://user-images.githubusercontent.com/52135169/101819080-c49c3400-3af2-11eb-9b48-0c6934266b6e.jpeg)
> > And yes, I got the issue resolved!!!
> 
> Nice! I plan on closing this issue soon, but I'd like to know what you did to solve it if you have time. That way if someone has a similar issue I can assist them in the future

[Here is the solution that worked for me.](https://github.com/barrykn/big-sur-micropatcher/issues/142#issuecomment-739626645)

**Comment by moosethegoose2213** [comment]
Thank you! I am now going to close this issue, thank you for using the Automator!
