### ISSUE TITLE
EFI boot and Post Install READ ME update?

### ISSUE THREAD

**Issue by jeffstumpf** [moosethegoose2213/automator-for-barrykn-micropatcher#12]
I no longer see a stand alone volume named EFI and I no longer see a Post-Install Automator with my MacPro5,1 (Mid-2010). The readme still has the select EFI boot and do Post-Install. Is that now built-in or is my MacOS 112.1 Installer that was created by this MicroPatcher Automator have an issue? Since everything seems OK. I'm guessing with the latest version, it is doing this in the background

**Comment by moosethegoose2213** [comment]
There was an issue when creating the usb (install-servers must have failed) as this isn't built in. If you try again it should be there.

**Comment by jeffstumpf** [comment]
Ok. Will do. If it still happens, I will let you know

Regards,
Jeff Stumpf
jeffstumpf@icloud.com
