### ISSUE TITLE
Empty password is not accepted

### ISSUE THREAD

**Issue by jensdepuydt** [moosethegoose2213/automator-for-barrykn-micropatcher#14]
When trying to run the automator from 10.13, an empty password did not get accepted any time authorization was needed.
Only after setting the password, I was able to use the tool. 

Possibly some input verification prevents this.

**Comment by minh-ton** [comment]
Blank passwords are a huge security risk. We won't be releasing a fix or provide any work-around for that problem. The only thing that you can do is to set your Mac password properly in order to use the patcher.

**Comment by jensdepuydt** [comment]
Maybe at least mention this or give a warning. Currently there is no feedback, the prompt just re-appears. This was just for a test (so no real security risk here) but it took quite some time to figure out that an empty password was not accepted.
