### ISSUE TITLE
simplify installation process

### ISSUE THREAD

**Issue by Ausdauersportler** [moosethegoose2213/automator-for-barrykn-micropatcher#2]
Since a download of the micro patcher ends up normally in the ~/Downloads folder why you ask user to move the patcher folder to the ~/Desktop manually (it is an automator :-) )

BTW: Great work!!

**Comment by moosethegoose2213** [comment]
I was also suggested by someone else who has been a big help with this project to move it too. They suggested moving it to a tmp folder. I might be able to check downloads and desktop, then if it isn't in either to download it to the tmp folder. This may come in a future release, but I'm not sure when. It wouldn't be a difficult thing to implement, but I don't have much time at the moment, as my finals are approaching rather quickly

**Comment by minh-ton** [comment]
@moosethegoose2213 Why not? Downloading to /tmp is way better...

**Comment by moosethegoose2213** [comment]
> @moosethegoose2213 Why not? Downloading to /tmp is way better...

Thats why I had said "I might be able to check downloads and desktop, then if it isn't in either to download it to the tmp folder" and that I might put it in a future release when I have time.

**Comment by moosethegoose2213** [comment]
@Ausdauersportler I have updated the automator, and it should now have the option to download it to wherever you want. If you try it in the future, let me know how it goes! I appreciate the feedback
