### ISSUE TITLE
Where's my cut?

### ISSUE THREAD

**Issue by ghost** [moosethegoose2213/automator-for-barrykn-micropatcher#4]
I DEMAND MY CREDIT!!! I CO-CREATED THIS!!! I NEED ACCESS AND RIGHT TO UTILIZE!!!

**Comment by ghost** [comment]
I NEED My CUT NOWWWWWWW!!! I DESERVE THIS JUST AS MUCH AS YOUU!

**Comment by moosethegoose2213** [comment]
You were already given credit, you know this. You are in the readme. And you are able to utilize this with credit, this is an open-source project. If you do utilize this, please give credit and follow the terms of the license. Thank you!
