### ISSUE TITLE
macOS 11.1 Downloading, not 11.2

### ISSUE THREAD

**Issue by ghost** [moosethegoose2213/automator-for-barrykn-micropatcher#8]
(Yes, I'm using the patcher even though I said I never would)
I don't know if this is intended, but for some reason the app is downloading 11.1 instead of 11.2. If this is intended, then pardon me, but I just want to throw it out there that not the newest version is downloading for me. Is anyone else experiencing this?

**Comment by ghost** [comment]
I'm using v2.0

**Comment by moosethegoose2213** [comment]
Thank you for informing us of this issue, we'll look into it. I'll keep this issue open until its fixed, thank you for the cooperation.

**Comment by ghost** [comment]
No problem. Please let me know if it's only a "me" issue or if it's something that is universal. I am running on an Early 2011 13" MacBook Pro with a 2.3ghz Core i5.

**Comment by minh-ton** [comment]
@MacHacJac Try downloading again, I don't think this is a patcher bug because the log still shows the 11.2 link. 
![image](https://user-images.githubusercontent.com/37860569/107873299-29557f80-6ee4-11eb-9817-4430c4de460e.png)

**Comment by ghost** [comment]
Yeah I redownloaded the automator and that one downloaded 11.2
