### ISSUE TITLE
Autoresume for installer download?

### ISSUE THREAD

**Issue by oladime** [moosethegoose2213/automator-for-barrykn-micropatcher#9]
Hi, I would appreciate it if you could include in your patcher a means of resuming downloads. Where I live, the network is slow and patchy, and many breaks occur. It would make life easier for me, and many others, I think. Thank you very much

**Comment by moosethegoose2213** [comment]
Sadly, that isn't something that is possible at this time. With Catalina and older, Apple provides different parts of the installer on the server so it's easier to implement a "Resume download" thing, but with Big Sur it's just a single InstallAsssistant.

**Comment by oladime** [comment]
Thank you for the response. Much obliged.
